### ISSUE TITLE
Changing an input triggers immediate querying of API

### ISSUE THREAD

**Issue by tripu** [mariaadobos/drugs-interactions-checker#7]
The API is queried as soon as any change occurs in any of the input fields. It is not *incorrect*, but causes lots of queries to fire rapidly, until the user is done typing the name of the drug. Disadvantages of this are: unnecessary network traffic; possible delays in refreshing the UI in the meantime; and it's much easier that we hit the limits of the public API (ie, the max. no. of queries available until we're “banned”).

Ideally, this should be [debounced](https://davidwalsh.name/javascript-debounce-function), say triggering the HTTP request only once every 0.5 seconds or so.

**Comment by mariaadobos** [comment]
@tripu Thank you so much for your advice, I´ll work on it!
